-- V4__modificacoes_cultivo_cpf.sql
-- No-op: this migration was Oracle-specific (VITS_ORC_* tables / sequences).
-- The current schema is created in V1 for USUARIOS_VITS/LOTES/EVENTOS_CULTIVO/SIMULACOES.
-- This file is intentionally left as a no-op to preserve Flyway history.
